apiVersion: v1
kind: Pod #Tipo de recurso
metadata:
  name: songs
spec:
  containers:
    - image: songs-ms
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      name: songs-ms
      ports:
        - containerPort: 4000
          name: http
          protocol: TCP
      imagePullPolicy: IfNotPresent

